### ISSUE TITLE
[watch_connectivity_garmin] Exception on sendMessage for Android

### ISSUE THREAD

**Issue by ILYA-2606** [Rexios80/watch_connectivity#11]
Code example:
```dart
final watch = WatchConnectivityGarmin();
await watch.initialize(GarminInitializationOptions(applicationId: 'xxx', urlScheme: 'yyy'));
await watch.sendMessage(message);
```
Exception:
`No implementation found for method sendMessage on channel watch_connectivity_garmin`

When will you add an implementation of this method? Without it, it is difficult to imagine integration with an application for Garmin :)

**Comment by Rexios80** [comment]
That method has an implementation...

**Comment by Rexios80** [comment]
The only thing Garmin doesn't support is application content

**Comment by Rexios80** [comment]
Where are you calling that method?

**Comment by Rexios80** [comment]
Feel free to reopen this if you want to continue troubleshooting
