### ISSUE TITLE
Swift Compiler Error (Xcode): Type 'WatchSessionDelegate' does not conform to protocol 'WCSessionDelegate'

### ISSUE THREAD

**Issue by demarilymd** [Rexios80/watch_connectivity#13]
I get this error when attempting to build the app from `flutter build ios`. I know that you include the required protocols for `sessionDidBecomeInactive` and `sessionDidDeactivate`. I also include the protocol `activationDidCompleteWith` in the watch os code.

**Comment by Rexios80** [comment]
Duplicate of #9

**Comment by demarilymd** [comment]
I don't believe this is a duplicate. I do not use sessionDidBecomeInactive and sessionDidDeactivate in my watch apps code. Why do you think this is a duplicate?

**Comment by Rexios80** [comment]
Because it's the same error. Does the example app in this repo compile? If it does then it's a duplicate issue.

**Comment by Rexios80** [comment]
Are you 100% positive your delegate is in the watch target and not the phone?

**Comment by Rexios80** [comment]
Can you send a screenshot of the file tree in Xcode

**Comment by demarilymd** [comment]
<img width="383" alt="image" src="https://github.com/Rexios80/watch_connectivity/assets/121904081/8c08fbd6-dbc4-43d7-8ad1-f391ac4ce7d0">

**Comment by demarilymd** [comment]
Also, for more context, I was able to create a new ios app with an added watchos app that uses your example code successfully.

**Comment by demarilymd** [comment]
This link states that watchos apps are created differently after iOS 13
https://developer.apple.com/forums/thread/716111

**Comment by demarilymd** [comment]
Here is my code for the delegate class
<img width="937" alt="image" src="https://github.com/Rexios80/watch_connectivity/assets/121904081/5cced75d-ccf2-489a-87fc-476a3c5ef0dc">

**Comment by Rexios80** [comment]
Why do you have those methods in an extension

**Comment by demarilymd** [comment]
This is a habit from when I was a iOS developer.

**Comment by Rexios80** [comment]
Well if the code that's causing problems is in the watch app that's outside the scope of this plugin. If a fresh project works then it's something with your project setup. Maybe try deleting the watch target and recreating it?

**Comment by Rexios80** [comment]
One thing I would check is see if the file's target is actually the watch target. You can check in the sidebar. (Idk how you would get it into the folder without that being the case but idk what else would be wrong)

**Comment by demarilymd** [comment]
Can you try to create a new flutter project that uses Xcode 15?

**Comment by demarilymd** [comment]
Ok, I can experiment with different versions of Xcode until then. What Xcode version did you create the plugin with?

**Comment by Rexios80** [comment]
13 something probably

**Comment by Rexios80** [comment]
But it's definitely possible for it to work with Xcode 15 because I use it in a project that still builds fine

**Comment by Rexios80** [comment]
I deleted and recreated the watch target in the example app using Xcode 15.0 with no issues. The code for that is on the develop branch.

**Comment by Rexios80** [comment]
Actually I just merged it into master so no one gets confused by the old example

**Comment by demarilymd** [comment]
I was able to get my new project built as well. I had to make some changes to the build phases and project but I got it to work! Did you have to make any changes as well?

**Comment by Rexios80** [comment]
I had to a while ago but that should be unrelated to the error you were getting

**Comment by runoob-coder** [comment]
<img width="1936" height="514" alt="Image" src="https://github.com/user-attachments/assets/15ecda26-17a6-41b2-b5df-b77919af7021" />

```swift
// add this line
import Combine
```

<img width="1334" height="590" alt="Image" src="https://github.com/user-attachments/assets/649549d8-8674-4e25-ae7a-979692ebd64f" />
