### ISSUE TITLE
Can watch_connectivity be used to read the heart rate?

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [Rexios80/watch_connectivity#18]
Can watch_connectivity be used to read the heart rate from an Android or Apple watch in real time?

**Comment by Rexios80** [comment]
It can be used in the process yes, but by itself no. You'll need the `workout` plugin to actually read the data from an Android watch, and a native SwiftUI app for Apple Watch.

**Comment by FluffyBunniesTasteTheBest** [comment]
@Rexios80 Thank you very much for the clarification.
