### ISSUE TITLE
How to React to session.receivedContext Outside the Body View in Swift?

### ISSUE THREAD

**Issue by callmephil** [Rexios80/watch_connectivity#20]
Hi there,  
I'm new to Swift and am having trouble reacting to `session.receivedContext` outside of the body view. In your example, you display the data using:

```swift
Text("Received context: \(session.receivedContext.description)")
```

This works fine for displaying the context, but I would like to execute some methods instead, such as:

```swift
func reset() {
    // Reset logic here
}
```

Here are the approaches I've tried:

### Attempt 1:

```swift
.onAppear() {
    Task {
        for await newContext in session.$receivedContext.values {
            print("Received new context in onAppear: \(newContext)")
            reset()
        }
    }
}
```

### Attempt 2:

```swift
.onReceive(session.$receivedContext, perform: { newContext in
    print("Received new context: \(newContext)")
    reset()
})
```

However, neither approach seems to work. The printed message does not show up in the console, and `reset()` is not being triggered.

For context, this is my Flutter code that sends the message:

```dart
Future<void> startNewMatch() async {
    try {
        // await _watch.updateApplicationContext({"data": "reset"});
        await _watch.sendMessage({"data": "reset"});
    } catch (e, trace) {
        debugPrint(['Failed to send message: $e', trace.toString()].join('\n'));
    }
}
```

What could I be missing here? How can I correctly react to changes in `session.receivedContext` and trigger a method like `reset()`?

**Comment by Rexios80** [comment]
Sorry, but this is not the place to ask for help with SwiftUI

I would think `onReceive` would work, but maybe you need `onChange` instead

Also these calls will only work if the view they are attached to is rendered
