### ISSUE TITLE
[example-ios] Release build not working

### ISSUE THREAD

**Issue by socsob** [Rexios80/watch_connectivity#21]
I spent an embarrassing amount of time figuring out why I could not install the watch app on my physical watch through the Apple "Watch" app off of a release build. Updating the Supported platforms to be watchOS for the Watch App target was the fix I needed. Hope this helps anyone else trying to setup from the example.

<img width="652" alt="Screenshot 2024-12-17 at 11 48 43 AM" src="https://github.com/user-attachments/assets/93642db9-8c36-4024-9707-46702cbba82d" />

**Comment by Rexios80** [comment]
If the example app works then this is a non issue
