### ISSUE TITLE
Release Android not receiving callback

### ISSUE THREAD

**Issue by butterbrain** [Rexios80/watch_connectivity#8]
I had a problem when, in release, the android app was not getting data sent from the garmin.

Turns out it was because of code obviscation, to fix; I changed my build.gradle to not minify code
release {
    signingConfig signingConfigs.release
    shrinkResources false
    minifyEnabled false
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}

and added a proguard file to leave the classnames required alone.
[proguard-rules.txt](https://github.com/Rexios80/watch_connectivity/files/11371078/proguard-rules.txt)

which would actually be called proguard-rules.pro

**Comment by Rexios80** [comment]
Disabling minify is not a solution

**Comment by Rexios80** [comment]
Disabling minify is a last ditch effort if all else fails. To actually fix this we need to figure out what classes we need to keep and add them to the proguard rules. Right now those proguard rules you gave aren't accomplishing much since you disabled minify anyways.

**Comment by imfelixng** [comment]
Hi @Rexios80 
 I use this package for debug mode, it works fine.
 but when release the android don't receive data from watch.
 
 Android Side & Watch Side is same config and use the same keystone
 
 > app/build.gradle
``` app/build.gradle
   signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
```

> proguard-rules.pro
```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-keep class * extends com.google.protobuf.GeneratedMessageLite { *; }
```

**Comment by Rexios80** [comment]
Both apps have the same bundle id?

**Comment by Rexios80** [comment]
Also does the example app work?

**Comment by butterbrain** [comment]
I might be wrong, but it's my interpretation that code minification will reduce the java classes used to something other than their original name. Therefore, the call cannot be routed properly to the class via reflection.
Adding...
-keep class com.garmin.android.connectiq.** { *; }
to your proguard rules should stop the com.garmin.android.connectiq classes from being minified to 1.0.92.1 or whatever, fixing the call.

I would...
1. change minifyEnabled to false and build and test in release to check that minificaftion is your problem.
2. Turn modification back on and add the 'keep class' clause to the proguard file. Or, if you are a bit lazy and just want it working, add a comment to the build.gradle and leave minification off, maybe it's small enough already (O:
3. keep working the proguard rules file to the point at which it works in release... here are mine (which will be too many) if you want to try some - I basically just add rules to get it building and working and 'small enough' as that's all I need

## proguard-rules.pro
-keepattributes Signature
-keepattributes LineNumberTable,SourceFile
-renamesourcefileattribute SourceFile
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.firebase.** { *; }
-keep class com.garmin.android.connectiq.** { *; }
-keepattributes JavascriptInterface
-keepattributes Annotation
-dontwarn com.razorpay.**
-keep class com.razorpay.** { *; }
-optimizations !method/inlining/
-keepclasseswithmembers class * {public void onPayment*(...);}
-dontwarn io.flutter.embedding.**

Feel free to ignore - it's not my plugin and I am far from a proguard expert.

**Comment by imfelixng** [comment]
> Both apps have the same bundle id?

Yes, it is the same. it works fine on debug mode

**Comment by imfelixng** [comment]
> I might be wrong, but it's my interpretation that code minification will reduce the java classes used to something other than their original name. Therefore, the call cannot be routed properly to the class via reflection. Adding... -keep class com.garmin.android.connectiq.** { *; } to your proguard rules should stop the com.garmin.android.connectiq classes from being minified to 1.0.92.1 or whatever, fixing the call.
> 
> I would...
> 
> 1. change minifyEnabled to false and build and test in release to check that minification is your problem.
> 2. Turn minification back on and add the 'keep class' clause to the proguard file. Or, if you are a bit lazy and just want it working, add a comment to the build.gradle and leave minification off, maybe it's small enough already (O:
> 3. keep working the proguard rules file to the point at which it works in release... here are mine (which will be too many) if you want to try some - I basically just add rules to get it building and working and 'small enough' as that's all I need
> 
> ## proguard-rules.pro
> -keepattributes Signature -keepattributes LineNumberTable,SourceFile -renamesourcefileattribute SourceFile -keep class io.flutter.app.** { _; } -keep class io.flutter.plugin._* { _; } -keep class io.flutter.util._* { _; } -keep class io.flutter.view._* { _; } -keep class io.flutter._* { _; } -keep class io.flutter.plugins._* { _; } -keep class com.google.firebase._* { _; } -keep class com.garmin.android.connectiq._* { _; } -keepattributes JavascriptInterface -keepattributes Annotation -dontwarn com.razorpay._* -keep class com.razorpay.** { _; } -optimizations !method/inlining/ -keepclasseswithmembers class * {public void onPayment_(...);} -dontwarn io.flutter.embedding.**
> 
> Feel free to ignore - it's not my plugin and I am far from a proguard expert.

thank you, let me try

**Comment by imfelixng** [comment]
@butterbrain  You put it to the only phone side or both watch and phone

**Comment by imfelixng** [comment]
> Also does the example app work?

for watch, i built it with Kotlin, and  I only use the package on Android app

**Comment by butterbrain** [comment]
yeah - me too - but it's the same idea so if the watch doesn't work you could put it there too probably.

**Comment by imfelixng** [comment]
I solved the issue.
because I use internal testing for the watch app and Firebase distribution for the phone app.
It does not same signing key.
So I use internal testing for the phone app and it syncs fine.
