### ISSUE TITLE
Type 'WatchSessionDelegate' does not conform to protocol 'WCSessionDelegate'

### ISSUE THREAD

**Issue by phackford** [Rexios80/watch_connectivity#9]
I am getting this error when archive a project to push to TestFlight. everything runs fine on the simulators.  

Showing Recent Messages
/WatchSessionDelegate.swift:12:7: Type 'WatchSessionDelegate' does not conform to protocol 'WCSessionDelegate'

WatchConnectivity.WCSessionDelegate:8:10: Protocol requires function 'sessionDidBecomeInactive' with type '(WCSession) -> Void'

WatchConnectivity.WCSessionDelegate:10:10: Protocol requires function 'sessionDidDeactivate' with type '(WCSession) -> Void'

**Comment by Rexios80** [comment]
What's your minimum iOS version target?

**Comment by phackford** [comment]
14

**Comment by Rexios80** [comment]
Can you get a screenshot of where Xcode says that error is?

**Comment by hifiaz** [comment]
i got this error also, when build ipa, file WatchSessionDelegate.swift i got from example folder
<img width="711" alt="Screenshot 2023-08-07 at 18 26 43" src="https://github.com/Rexios80/watch_connectivity/assets/20653803/54b96922-7e5e-4fb1-9fd4-220d6478f0e0">

**Comment by Rexios80** [comment]
Is that error even in code that's part of this plugin?

**Comment by Rexios80** [comment]
Well since it's not the plugin that's actually the problem, what's your watchOS target?
